name: Cache Workflow

on:
  push:
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-ba4c0c5

      - name: prime-cache-ba4c0c5
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Done
        run: echo "Caching complete"
